#pragma once

#include <algorithm>
#include <array>
#include <string_view>

namespace Mafia1Online::Shared::World {
    // Directory names with both scene.4ds and tree.klz in the Steam a1.dta
    // archive. The game's menu-only scenes (00menu, autosalon and
    // carcyclopedia) have no collision tree and are not gameplay missions.
    inline constexpr auto kStockMissions = std::to_array<std::string_view>({
        "02normancela",
        "extreme",
        "fmv intermezzo05",
        "fmv konec",
        "freeitaly",
        "freekrajina",
        "freekrajinanoc",
        "freeride",
        "freeridenoc",
        "intermezzo02",
        "intermezzo03",
        "intermezzo4",
        "intro",
        "mise01",
        "mise02-saliery",
        "mise02-ulicka",
        "mise02a-taxi",
        "mise03-morello",
        "mise03-saliery",
        "mise03-salierykonec",
        "mise04-krajina",
        "mise04-mesto",
        "mise04-motorest",
        "mise04-saliery",
        "mise05-mesto",
        "mise05-saliery",
        "mise06-autodrom",
        "mise06-mesto",
        "mise06-oslava",
        "mise06-saliery",
        "mise07-saliery",
        "mise07-sara",
        "mise07b-chuligani",
        "mise07b-saliery",
        "mise08-hotel",
        "mise08-kostel",
        "mise08-mesto",
        "mise09-krajina",
        "mise09-mesto",
        "mise09-prejimka",
        "mise09-saliery",
        "mise10-letiste",
        "mise10-mesto",
        "mise10-saliery",
        "mise11-mesto",
        "mise11-saliery",
        "mise11-vila",
        "mise12-garage",
        "mise12-mesto",
        "mise12-saliery",
        "mise13-mesto",
        "mise13-mesto2",
        "mise13-restaurace",
        "mise13-zradce",
        "mise14-mesto",
        "mise14-parnik",
        "mise14-saliery",
        "mise15-mesto",
        "mise15-pristav",
        "mise15-saliery",
        "mise16-krajina",
        "mise16-letiste",
        "mise16-mesto",
        "mise16-saliery",
        "mise17-mesto",
        "mise17-saliery",
        "mise17-vezeni",
        "mise18-mesto",
        "mise18-pristav",
        "mise18-saliery",
        "mise19-banka",
        "mise19-mesto",
        "mise19-pauli",
        "mise20-galery",
        "mise20-mesto",
        "mise20-pauli",
        "tutorial",
    });

    constexpr bool IsStockMission(std::string_view name) {
        return std::find(kStockMissions.begin(), kStockMissions.end(), name) != kStockMissions.end();
    }
} // namespace Mafia1Online::Shared::World
